feat(FEC-13362): add events for kava
kaltura/playkit-js-downloads pull request #35
Opened 2023-12-07 13:20 UTC by lianbenjamin

### Description of the Changes

add new event for kava- when downloading an item.

Solves FEC-13362

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-12-08 11:30 UTC, semarche-kaltura requested changes
why PR contains changes for yarn.lock but not for package.json?

2023-12-10 07:33 UTC, lianbenjamin commented
@semarche-kaltura when i did yarn install, the yarn.lock changed and at first i didn't pushe it to PR, but then the install dep in the test jobs has failed with error "error Your lockfile needs to be updated", so then when i pushed it- the jobs passed.

2023-12-10 08:25 UTC, SivanA-Kaltura requested changes

2023-12-10 08:25 UTC, SivanA-Kaltura commented on src/components/download-item/download-item.tsx
> +const {withPlayer} = ui.Components;
if you know how to resolve the error, don't use ts-ignore

2023-12-11 11:30 UTC, SivanA-Kaltura approved these changes

2023-12-11 12:45 UTC, semarche-kaltura approved these changes

2023-12-11 12:50 UTC, merged